# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180226_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendees',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Attendees'),
        ),
    ]
