version: '3.8'

services:
  db:
    image: postgres

  web:
    image: git.zakscode.com/ztimson/oacpl:latest
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
