# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_law', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Area of Expertise',
                'verbose_name_plural': 'Areas of Expertise',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('cases', models.ManyToManyField(blank=True, to='case_law.Case')),
                ('expertise', models.ManyToManyField(to='expert_witnesses.AreaOfExpertise')),
            ],
        ),
    ]
