# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import expert_witnesses.models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_witnesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'permissions': (('view_cv', 'Can view CV'),)},
        ),
        migrations.AddField(
            model_name='expert',
            name='CV',
            field=models.FileField(blank=True, null=True, upload_to='cv', validators=[expert_witnesses.models.Expert.validate_file_extension], verbose_name='CV'),
        ),
    ]
