# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_auto_20180105_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
