# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_auto_20180114_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Newsletter')),
            ],
        ),
        migrations.AddField(
            model_name='newsletter',
            name='attachments',
            field=models.ManyToManyField(to='newsletters.Attachment'),
        ),
    ]
