# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 23:23
from __future__ import unicode_literals

import case_law.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_law', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='pdf',
            field=models.FileField(upload_to='case_law', validators=[case_law.models.Case.validate_file_extension], verbose_name='PDF'),
        ),
    ]
