# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180106_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topic',
            new_name='thread',
        ),
    ]
