# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('front_page', models.BooleanField(default=False)),
                ('image', models.ImageField(default='portraits/silhouette.png', upload_to='portraits')),
                ('joined', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='attorney',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charter_members.Position'),
        ),
    ]
