# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 06:53
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('charter_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='biography',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
