# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charter_members', '0003_auto_20180114_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order On Front Page'),
        ),
    ]
