# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charter_members', '0005_auto_20180123_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='call_to_bar',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
