# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charter_members', '0007_auto_20180124_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charter_members.Position'),
        ),
    ]
