# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 03:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charter_members', '0008_auto_20180124_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
