# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0002_auto_20180131_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
