# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0003_auto_20180131_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='help_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
